//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTwain.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NTwain.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value type for {0}..
        /// </summary>
        internal static string BadValueType {
            get {
                return ResourceManager.GetString("BadValueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capability has invalid container type {0}..
        /// </summary>
        internal static string CapHasBadContainer {
            get {
                return ResourceManager.GetString("CapHasBadContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capability contains no data..
        /// </summary>
        internal static string CapHasNoData {
            get {
                return ResourceManager.GetString("CapHasNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string value has exceeded the maximum length allowed..
        /// </summary>
        internal static string MaxStringLengthExceeded {
            get {
                return ResourceManager.GetString("MaxStringLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to allocate requested memory..
        /// </summary>
        internal static string MemAllocError {
            get {
                return ResourceManager.GetString("MemAllocError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message loop has not started yet..
        /// </summary>
        internal static string MsgLoopUnavailble {
            get {
                return ResourceManager.GetString("MsgLoopUnavailble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source name is required..
        /// </summary>
        internal static string SourceRequired {
            get {
                return ResourceManager.GetString("SourceRequired", resourceCulture);
            }
        }
    }
}
